name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js v14.17.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.1'
          
      - name: Install
        run: |
          npm install
        
      - name: publish vscode-plugin-marketplace
        run: |
          vsce publish -p 5stsj3ebtg67tbl6tplw6l2yttor2ab7k6bd6kyele54flzbqygq

