name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js v14.17.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.1'
          
      - name: Install
        run: |
          npm install
        
#       - name: publish vscode-plugin-marketplace
#         run: |
#           vsce publish -p 5stsj3ebtg67tbl6tplw6l2yttor2ab7k6bd6kyele54flzbqygq

      - name: echo-test
        run: |
          echo 打印开始
          ls
          echo 打印完毕

      - name: Publish VS Code Extension
      # You may pin to the exact commit or the version.
      # uses: HaaLeo/publish-vscode-extension@a7981039f3dd0bd407a71c10b11f3cb79cb249d4
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          # Personal access token
          pat: ${{ secrets.PUBLISHER_TOKEN }}
